### ISSUE TITLE
Cant import part from shared library

### ISSUE THREAD

**Issue by K0ertis** [rca/PySPICE#21]
Hi! I compiled the shared library from ngspice (master) and enabled shared library flag. 
Successfully found those on my Ubuntu16.04 under **/usr/local/lib** :

`libngspice.so,
libngspice.so.0,
libngspice.so.0.0`

In jupyter I included the library as following as in the example of the diode in 8.2.1 and changed this line to:
`
libraries_path = os.path.join(os.path.dirname('/usr/local/lib/'), 'libraries')
 `
`
spice_library = SpiceLibrary(libraries_path)    
`

When I try `spice_library['1N4148'] ` I get the key error because spice_library has no entry of this part. 
When I open interactive python console and look into the class of spice_library I have only two empty subclasses:
`models
 subcircuits`

Could anyone tell me what I am missing?

**Comment by drbitboy** [comment]
It looks like you are conflating two identically-named packages called SPICE:  one is an electronics simulation package, IIRC; the other is a toolkit for working with spacecraft mission geometry and events written by the Navigation and Ancillary Information Facility at the Jet Propulsion Laboratory (NAIF/JPL).

PySPICE is related to the latter.

**Comment by K0ertis** [comment]
Wow I mixed this up! Those are indeed named both PySpice and PySPICE. Thank you for the hint!
